tables/utilsextension.pyx
https://github.com/FrancescAlted/blosc/issues/3 has been
resolved in version 1.5. Since version 1.5 is now bundled
with PyTables, remove the check.
I built a Fedora package with a similar patch, using an external blosc 1.5.2, and tests pass on i686, amd64 and arm32.
=> Blosc supports all architectures

tables/node.py, tables/tests/test_links.py
I just noticed that it's not currently possible to create a new node whose parent is a softlink to another group:
```python
In [1]: tmpf = tables.open_file('/tmp/test.hdf5', 'w')
In [2]: g1 = tmpf.create_group('/', 'group1')                                                                                                                                                                        
In [3]: link_g1 = tmpf.create_soft_link('/', 'link_group1', g1)                                                                                                                                                      
In [4]: arr = tmpf.create_array(link_g1, 'test', obj=[1, 2, 3]) …
```
=> Fix softlink as parent group

doc/source/usersguide/libref/top_level.rst
The global variable `hdf5_version` appeared twice in the docs.
This removes one of the copies.
=> Remove duplicate `hdf5_version` in Top-level docs

tables/table.py
As reported in #343: Nested iterators don't work as originally shown in the example.
The docstring of Table.where() has been correctly modified in 30f89b9fc5.
However, some references to that example were still in other docstrings.
=> Remove leftover references to 'nested iterators'

.travis.yml, README.rst, RELEASE_NOTES.txt, doc/source/usersguide/installation.rst, requirements.txt, setup.py, tables/req_versions.py
Also, Cython is not a requirement anymore and minimum versions for hdf5/numpy/numexpr have been bumped up to 1.8.7, 1.7.1. and 2.4.1 respectively.
This is just for some quick discussions, as I would like to merge it pretty quick.
=> Setup.py requires now setuptools

c-blosc/hdf5/blosc_filter.c
The implementation of H5Epush function has been modified in hdf5-1.8.15.
Now it raises an compilation warning that is turned into an error in Ubuntu 15.04 (and probably in Debian) due to compilation flags used to build the interpreter.
In the specific `-Werror=format-security`.
This PR addresses issue #443 by modifying the `blosc_filter.c` code.
Another option is to add `-Wno-format-security` to the C flags of utilsextension, hdf5extension and tableextension extensions:
```
extra_compile_args=CFLAGS + ['-Wno-format-security']
```
Note: this PR has still not been submitted upstream because I currently have a build problem with c-blosc and can't test the patch properly against the upstream master.
=> Fix compatibility with hdf5-1.8.15-pre7

RELEASE_NOTES.txt, doc/source/usersguide/installation.rst, setup.py
This PR adds to the `setup.py` script the ability to use the pkg-config package to find dependencies.
By default pkg-config is always used (if available), unless explicitly disabled.
This PR should also fix #442.
=> pkg-config support

tables/table.py, tables/tests/test_tables.py
Without a condition the entire table is appended to the destination
table.
Includes test for appending without a condition.
Fixes #376
=> Allow absence of condition for append_where

tables/link.py, tables/parameters.py
The missing blank line prevented proper syntax highlighting in the docs.
=> Fix two typos in docstrings.

doc/source/MIGRATING_TO_3.x.rst, tables/atom.py, tables/description.py, tables/flavor.py, tables/tests/test_types.py
In Python3 strings show up as dtype e.g. `'<U50'`. The current code only looks for a Python2-style `'S'`-kind, resulting in
```python
ValueError: unknown type: 'str1600'
```
upon calling e.g. `create_array` with a string array as `obj=` argument, since this case currently gets handed over to `from_type`.
=> Python3 Unicode string support in Atom.from_dtype

tables/table.py
Move docstring about remove_rows back to it (was mistakenly moved when adding remove_row in 0c3b923).
Clarify the effect of omitting the 'stop' for remove_rows.
Clarify that step is not supported (only None or 1).
Fix a typo.
Add example to remove_row to show equivalent remove_rows arguments.
=> Fix docstrings for remove_row(s)

tables/leaf.py, tables/table.py
A previous fix (for issues #319 and #409) for the size of nrowsinbuf calculated in _calc_nrowsinbuf was already checking specifically for the Table class. However, classes inheriting from Table encounter the same problem. This commit also fixes nrowsinbuf size for classes inheriting Table (issue #477).
=> Make _calc_nrowsinbuf in tables/leaf.py also check for classes inheriting Table

tables/file.py
Clarify what happens when where is a Node (from a different file). See #478
=> Improve docstring for get_node

tables/array.py, tables/index.py, tables/table.py, tables/tests/test_tables.py, tables/vlarray.py
This is a bit weird, it was prompted by #475 and #43.
The problem (or part of it) lies in that if
key  = numpy.uint64(10)
`is_idx(key)` will return `True` but then
self._process_range(key, key + 1, 1)
fails because `key + 1 == 11.0` (try it yourself).
The uptake is that indices need to be casted in some way. I decided to use
`operator.index` because that's what Python uses internally when something is
used as an index.
Interestingly enough #43 got fixed accidentally: `Array._interpret_indexing`
fails because `_process_range` fails, just like above. But then
`Array.__getitem__` goes on trying different strategies and finally
`_fancy_selection` does the cast.
This PR is for the upcoming 3.2.2
Closes #475, #43
=> Cast selection indices to integer

doc/source/usersguide/tutorials.rst
Added a caveat that Row.update does not work if the loop is broken with break statement. Related to Issue #404
=> + caveat on Row.update (doesn't work with break)

doc/source/index.rst
=> Update link to NumFOCUS projects page

tables/utilsextension.pyx
=> DOC: 'blosc' is a valid input to which_lib_version

tables/utils.py
Set ```entries_to_remove``` to ```1``` if ```self.maxentries // 10 < 0``` (using ```max```)
=> Ensure cache entries are removed if fewer than 10 entries in the cache - fix for #529

tables/index.py
Tested with cython 0.23.4+git4-g7eed8d8-1 from Debian.
The Cython documentation suggests that cdef classes can't
inherit from Python classes, perhaps this had an effect in the
case of multiple inheritance.
Fixes #532
=> Fixes segfaults in a number of test cases that use index.Index

c-blosc/hdf5/blosc_filter.c
This creates problems when using an external blosc library that is >= 1.5.
=> Initialize compname so that blosc_compress_ctx can use a default

tables/conditions.py, tables/table.py, tables/tableextension.pyx, tables/tests/test_queries.py
When using numexpr with the Intel MKL (default for conda packages for numexpr>2.4.6) ALL ```table.read_where()``` queries which use functions are broken.
Issue: #534 
See also: pydata/numexpr#210 
numexpr (with MKL support) uses VML functions which require contiguous memory. tables are non-continguous so a copy operation is needed. Therefore the ex_uses_vml kwargs needs to be passed by ```conditions.call_on_recarr()```.
This fixes my testcase.
~~This breaks many unittests~~ 
ToDo:
=> fix read_where() query with functions when numexpr uses Intel MKL

tables/tests/test_indexvalues.py
Make sure the tests in test_indexvalues.py use buffersizes (number of rows in buffer, table.nrowsinbuf) that are a multiple of ```chunkshape[0]```
fixes #538 
This affects the TestCases below, which may have been *designed* for ```buffersize % chunksize != 0```: 
```
TestCase10b
TestCase13a
TestCase14a
```
=> Fix test_indexvalues --heavy testcases that use illegal chunksize

setup.py
Add lib64 to posix search path. Fixes #507.
=> Add lib64 to posix search path. Fixes #507.

tables/file.py
It is not true that native Python sequences are accepted.
Only numpy.ndarray arrays with named dtypes are allowed.
See the if statement after the docstring:
```python
if not isinstance(obj, numpy.ndarray):
raise TypeError('invalid obj parameter %r' % obj)
```
=> Fix docstring for create_table keyword obj

bench/bench-pytables.sh, bench/pytables_backend.py
pytables_backend had hard-coded paths that are used as workspace by benchmark executer. The runtime makes an assumption about the existence of those hard-coded paths. These changes should ensure that those paths exist before benchmarks are executed.
@FrancescAlted
=> fix bench-pytables.sh 

c-blosc/ANNOUNCE.rst, c-blosc/CMakeLists.txt, c-blosc/README.rst, c-blosc/RELEASE_NOTES.rst, c-blosc/RELEASING.rst, c-blosc/appveyor.yml, c-blosc/blosc/blosc.c, c-blosc/blosc/blosc.h, c-blosc/examples/multithread.c, c-blosc/examples/noinit.c, c-blosc/tests/CMakeLists.txt, c-blosc/tests/test_api.c, c-blosc/tests/test_common.h, c-blosc/tests/test_compressor.c, c-blosc/tests/test_noinit.c, c-blosc/tests/test_nolock.c, c-blosc/tests/test_nthreads.c
This is an update of C-Blosc sources to latest 1.9.2, where some fixes and performance improvements are done.  Also, C-Blosc 1.9.2 does honor environment variables to change the behavior of the compressor.  For details see:  https://github.com/Blosc/c-blosc/pull/164/files#diff-ef50c2e1ff36cb90b51cbba3ebb3ad04L156
If there are no complains, I will merge this by tomorrow.
=> Internal c-blosc bumped to 1.9.2

tables/nodes/tests/test_filenode.py
Small fix to allow all tests to pass on current `master` 
`import Image` does not work. Use `from PIL import Image` instead.
http://stackoverflow.com/questions/19230991
=> Fix pillow/PIL import. Fix test02_UseImageAsFile

tables/atom.py
This is a version of #553 against `master`.
This fixes: #552 
The bug is caused by `lib2to3` changing `basestring` to `str` on python3.
This fix also explicitly allows strings to make sure we do not break the API. 
This allows `bytes`  (which includes `str` in python 2) and `unicode` for python 2. 
This is converted to `bytes` and `str` for python 3 by `lib2to3`.
ToDo:
=> Fix vlstringatom on python3 after lib2to3

setup.py
When comping on aarch64, setup.py fails with:
Exception: py-cpuinfo currently only works on X86 and some ARM CPUs.
Assume that the CPU does not support SSE2 or AVX in importing cpuinfo fails
and continue.
(Package builds fine and tests pass with this patch:
https://kojipkgs.fedoraproject.org//packages/python-tables/3.3.0/1.fc26/data/logs/aarch64/build.log)
=> setup.py: gracefuly handle cpuinfo failure

tables/idxutils.py
Blind attempt to address failing tests of pandas on i386, e.g.
https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=i386&ver=0.19.1-1&stamp=1479504883
Somewhat a blind shot but I thought that if int and even float are kosher enough, long should be as good ;)   With this change corresponding tests in pandas have passed just fine
=> ENH(BF?): allow for  long type in nextafter

.travis.yml
CPython 3.6 was released 23-12-2016.
Add 3.6 to tests.
(`pytables-3.3.0` packages for python 3.6 already live on conda-forge)
=> Test against python 3.6

appveyor.yml, setup.py
Add python 3.6 (using `conda-forge` channel) to appveyor.
=> Test against python 3.6 on appveyor

tables/attributeset.py, tables/description.py, tables/exceptions.py, tables/file.py, tables/filters.py, tables/group.py, tables/index.py, tables/indexes.py, tables/leaf.py, tables/link.py, tables/table.py, tables/unimplemented.py
Uses class decorator `@python_2_unicode_compatible` from `six`.
```
A class decorator that takes a class defining a __str__ method. On
Python 3, the decorator does nothing. On Python 2, it aliases the
__str__ method to __unicode__ and creates a new __str__ method that
returns the result of __unicode__() encoded with UTF-8.
```
Closes #514
=> Make non-ascii returning __str__ work on Python2

doc/source/usersguide/utilities.rst, tables/scripts/ptrepack.py, tables/tests/test_all.py, tables/tests/test_utils.py
Allow different file separators based on OS: ":" for
Linux/macOS and "," for Windows. Clarify documentation
(available via "ptreapck --help") accordingly.
Not test included. Need help on that. Any example ?
Resolves: #616
See also: commit 476a2f956322569efefa5d779b457d639b90a552
=> Allow Windows absolute file paths in ptrepack args

RELEASE_NOTES.txt, appveyor.yml, tables/scripts/ptdump.py, tables/scripts/ptrepack.py, tables/scripts/pttree.py, tables/tests/test_all.py, tables/tests/test_utils.py
ptdump, pttree and ptrepack use 'path:/group/node' as input.
On windows this could be: 'drive:\folder\filename:/group/node' (extra colon)
No testcase included.
Resolves: #616
See also: commit 476a2f956322569efefa5d779b457d639b90a552
=> Allow Windows absolute paths in ptutils args

appveyor.yml, doc/source/usersguide/installation.rst, setup.py
Use installed package if location not otherwise specified.
Add `--no-conda` flag to `setup.py` to disable.
Use CONDA_PREFIX\\Library on windows.
PEP8 fixes to setup.py
Remove HDF5_DIR etc from appveyor
This does not use `conda list`. This is the KISS way.  
Issues:
- It breaks finding packages using `pkg-config` inside a conda env, when the package is not in conda env but is installed on the system (with pkg-config info)
=> Detect conda env try to use conda packages

RELEASE_NOTES.txt, tables/group.py, tables/tests/test_tree.py
Implement `__dir__()` on group nodes to include in the list of autocompletions also those children that are named as valid python identifiers.
=> feat(group): autocomplete valid python-identifiers

RELEASE_NOTES.txt, tables/attributeset.py, tables/group.py, tables/tests/test_attributes.py, tables/utils.py
Similar to #624, implement also `AttributeSet.__dir__()`  to return in its autocompletion list those attributes that are named as valid python identifiers.
+ Docs updated.
+ Simple test-case.
+ Not suitable for PY-2 (no `__dir__()` in datamodel).
=> feat(attributes): __dir__() autocompletes also valid py-indentifiers

RELEASE_NOTES.txt, tables/group.py, tables/tests/test_attributes.py, tables/tests/test_tree.py
Since `tables.group.Group` class defines `__contains__()` and `iter__()` methods, it should also define `__getitem__()`, and work as a proper *container*.  
That would make the code below to work intuitively:
```python
>>> 'group 1' in hfile.root
>>> g1 = hfile.root['group 1']
>>> g1['some &^%&^* named group']._v_pathname 
/group 1/some &^%&^* named group
```
For the record, that must have been the purpose of #270.
Improv unique checks on `__dir__()` TCs.
=> Define `Group.__getitem__()` method

c-blosc/blosc/shuffle-avx2.c
While trying to build PyTables using icc/icpc, the build would fail with the following error:
```
error: identifier "_mm256_castsi128_si256" is undefined
_mm256_loadu2_m128i(const __m128i* const hiaddr, const __m128i* const loaddr)
^
test.c(5): error: expected a type specifier
_mm256_loadu2_m128i(const __m128i* const hiaddr, const __m128i* const loaddr)
^
test.c(5): error: expected a type specifier
_mm256_loadu2_m128i(const __m128i* const hiaddr, const __m128i* const loaddr)
^
test.c(5): error #141: unnamed prototyped parameters not allowed when body is present
_mm256_loadu2_m128i(const __m128i* const hiaddr, const __m128i* const loaddr)
^
test.c(8): error: identifier "loaddr" is undefined
_mm256_castsi128_si256(_mm_loadu_si128(loaddr)), _mm_loadu_si128(hiaddr), 1);
^
test.c(8): error: …
```
=> enable building PyTables with Intel compiler (icc/icpc)

doc/source/FAQ.rst, doc/source/project_pointers.rst, doc/source/usersguide/tutorials.rst
A few small fixes in the documentation,
* PEP8 in an example
* fixed broken URL to the sourceforge mailing list archive
* removed the "Old trac site" link as it is not working (but maybe there is a way to fix it)?
=> DOC small documentation fixes

tables/tableextension.pyx
`tables.tableextension.Table._convert_time64_()` divides by zero
when its called with an empty `nparr` array. This happens because
the `__next_indexed()` method tries to convert attributes an array
even if it is empty.
Fixes #653
=> Do not try to convert values of an empty array

.gitignore, tables/tests/test_basics.py, tables/utilsextension.pyx
PEP 519 defines a filesystem path protocol, and enhances Python builtin I/O functions to support "path-like" objects such as `pathlib.Path`s. As part of this PEP, the `os` module also gained a `fspath` function, which takes an arbitrary path-like object and returns a string.
If the os.fspath function is available (i.e. Python >= 3.6), use it to convert `filename` to a string inside `utilsextension.encode_filename`. This allows using `Path` objects in `tables.open_file`.
=> Add PEP 519 support

src/H5ARRAY.c, src/H5ARRAY.h, src/H5TB-opt.c, src/H5TB-opt.h, src/H5VLARRAY.c, src/H5VLARRAY.h, tables/array.py, tables/carray.py, tables/definitions.pxd, tables/earray.py, tables/file.py, tables/hdf5extension.pxd, tables/hdf5extension.pyx, tables/leaf.py, tables/table.py, tables/tableextension.pyx, tables/tests/test_timestamps.py, tables/vlarray.py
As mentioned on the mailing list, these are changes to optionally disable recording of ctime (metadata creation time) when creating datasets.  This makes it possible to get bitwise identical output from repeated runs of the same application, which is useful for regression testing, and also for working with build tools that use hashes for change detection.
Commit 6eace4d does the real work, accepting a track_times flag on dataset constructors and then using H5Pset_obj_track_times() to optionally disable time tracking when creating datasets.
One of the commits here (19df430) adds a .track_times property to the Leaf class so that users can retrieve the value, but I am not sure this is actually a good idea.  The property uses H5Pget_obj_track_times() to get the value of this flag after …
=> No track times

tables/array.py, tables/tests/test_attributes.py, tables/tests/test_earray.py, tables/tests/test_nestedtypes.py, tables/tests/test_types.py, tables/tests/test_vlarray.py
Changed `numpy.issubdtype(dt, int)` to `numpy.issubdtype(dt, np.signedinteger)` as suggested by the deprecation warning:
```text
In [2]: np.issubdtype(np.int32, int)
/localdisk/work/miniconda3/envs/np114/bin/ipython:1: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
#!/localdisk/work/opavlyk/miniconda3/envs/np114/bin/python
Out[2]: True
```
=> fixing Deprecation Warning from numpy.issubdtype

tables/vlarray.py
This PR prevents from reading all rows for each coord when indexing using a list (see [here](https://github.com/PyTables/PyTables/blob/develop/tables/vlarray.py#L836)). 
**Example on how to reproduce the error:**
Generating the hdf5 file
```python
import tables
import numpy as np
f = tables.open_file('test.h5', 'w')
input_node = f.create_vlarray(f.root, 'input',  tables.Float32Atom(shape=(30, )), 
"Input", expectedrows=1000)
for _ in range(1000):
input_node.append(np.random.randn(np.random.randint(5,100), 30))
f.close()
````
Reading non-continuous indexes
```python
import tables
f = tables.open_file('test.h5', 'r')
input_node = f.get_node('/input')
%timeit input_node[[0,1,2,33,634, 125]]
```
and you will get:
```
72.4 ms ± 14.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
``` …
=> Fix VLArray._read_coordinates

tables/__init__.py
=> Skip the DLL check when running from a frozen app

tables/expression.py, tables/tests/test_expression.py
Hopefully this fixes issue #651 
Actually I think this is more a workaround than a real fix...
I created the test `test02_out` in `test_expression.py`.
=> Fix slicing outside of data samples

tables/array.py, tables/carray.py, tables/earray.py, tables/file.py, tables/table.py, tables/vlarray.py
Flags for time tracking control have been added in v3.4.3, not in 3.4.
=> Fix versionadded tags for v3.4.3

setup.py
re.split("\s*") has changed from splitting on 1 or more spaces in Python 3.6
(with a deprecation warning) to splitting on 0 or more spaces in Python 3.7.
In Python 3.7 this means it splits at every character.
With Python 3.6:
python -c "import re; print(re.split('\s*', '#define H5_VERS_MAJOR    1'))"
/opt/conda/lib/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
return _compile(pattern, flags).split(string, maxsplit)
['#define', 'H5_VERS_MAJOR', '1']
With Python 3.7b3:
python -c "import re; print(re.split('\s*', '#define H5_VERS_MAJOR    1'))"
['', '#', 'd', 'e', 'f', 'i', 'n', 'e', '', 'H', '5', '_', 'V', 'E', 'R', 'S', '_', 'M', 'A', 'J', 'O', 'R', '', '1', '']
=> Python 3.7 fix for re.split() in version detection

tables/tests/test_tables.py
While fixing fall-outs of changes to `numpy.rec.array`
(see https://github.com/numpy/numpy/issues/10344) I evidently missed
a spot which is now causing trouble. See
https://github.com/PyTables/PyTables/pull/664
I think I noted this in the aforementioned PR in a comment.
This PR is to make sure that `initRecArray` method produces list of
tuples, rather than list of lists, as an argument to `numpy.rec.array` constructor.
=> MAINT: Fixed test failures with Python 2.7 and NumPy 1.14.3

CITATION.bib
Hello :-)
How about including the snippet from https://www.pytables.org/FAQ.html#how-can-i-cite-pytables into the code? Additionally possible: using [`@software`](https://github.com/force11/force11-sciwg/issues/48#issuecomment-372022915) and [sync'ing this repo with Zenodo to get a DOI](https://guides.github.com/activities/citable-code/). What do you think?
=> Include citation in repo

doc/source/usersguide/optimization.rst
Also remove section about `expectedsizeinmb` and `VLArray`, as that parameter has changed to `expectedrows` in version 3.0.
=> Fix typos in optimization.rst

.travis.yml
Python 2.6 is not supported anymore, so that 'if' is never executed
=> Remove never-executed code from travis file

cpuinfo.py, setup.py
- Enables AVX2 in the blosc macros for Windows builds.
- Updates `cpuinfo.py` to version `4.0.0`.
- Protects entire `setup.py` with a `if __name__ == '__main__'` block to avoid `cpuinfo` issue related to multiprocessing: https://github.com/workhorsy/py-cpuinfo/issues/108
=> Add AVX2 support for  Windows

tables/index.py
I've run into a few instances where calling `Table.reindex()` fails with the following:
```
Traceback (most recent call last):
File "test_indexing.py", line 218, in <module>
test_query_times(fname)
File "test_indexing.py", line 138, in test_query_times
table.reindex()
File ".../env/lib/python3.6/site-packages/tables/table.py", line 2762, in reindex
self._do_reindex(dirty=False)
File ".../env/lib/python3.6/site-packages/tables/table.py", line 2745, in _do_reindex
indexedrows = indexcol._do_reindex(dirty)
File ".../env/lib/python3.6/site-packages/tables/table.py", line 3657, in _do_reindex
kind=kind, optlevel=optlevel, filters=filters))
File ".../env/lib/python3.6/site-packages/tables/table.py", line 3609, in create_index
tmp_dir, _blocksizes, _verbose)
File …
```
=> Ensure offsets are always an integer

tables/file.py
Fixes #733 (unittests fail on python 3.8a4)
Cache items are changed while looping over the cache items, this causes an
`Dictionary keys changed during iteration` error in python>=3.8.
This casts the cache to a list first and iterate over the list to prevent the error.
This might affect performance on very large HDF5 files where the nodecache may be very big. However this is only called while moving/renaming(?) a node:  [tables/group.py#L602](https://github.com/PyTables/PyTables/blob/a92a38c3c6d8a29e64ac12294a3a5e4847fea3d1/tables/group.py#L602) so IMO it should not be a significant problem.
=> Fix Dictionary keys changed during iteration in unittests on python 3.8a4

setup.py
python3.8 now warns about those. One solution would be to change each
of them to r'\s+' or '\\s+', but it turns out that using re is not
necessary at all, since the plain .split() does the exact same thing.
=> setup.py: remove improperly escaped regexps

bench/bsddb-table-bench.py, bench/recarray2-test.py, bench/search-bench.py, bench/searchsorted-bench.py, bench/searchsorted-bench2.py, bench/shelve-bench.py, bench/sqlite-search-bench.py, bench/stress-test.py, bench/stress-test2.py, bench/stress-test3.py, bench/table-bench.py, tables/index.py
`time.clock` will be removed in Python 3.8 after being deprecated in Python 3.3
```
$ python3.7 -c 'from time import clock; clock()'
-c:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
```
The Fedora linux distribution is starting to build Python packages with beta releases of Pyhton 3.8 in other to detect possible problems. This PR substitutes calls to `time.clock`, that will been removed in Python 3.8, with `time.perf_counter`
The related issue is #744
=> Replace deprecated time.clock with time.perf_counter

tables/tests/test_array.py, tables/tests/test_attributes.py, tables/tests/test_basics.py, tables/tests/test_create.py, tables/tests/test_earray.py, tables/tests/test_expression.py, tables/tests/test_indexes.py, tables/tests/test_indexvalues.py, tables/tests/test_numpy.py, tables/tests/test_tables.py, tables/tests/test_tablesMD.py, tables/tests/test_timestamps.py, tables/tests/test_vlarray.py
Note about half of these change functionality. I assume they were mistyped originally. 
self.assertTrue(type(b), numpy.ndarray)
=>
self.assertIsInstance(b, numpy.ndarray)
self.assertTrue(a1.maindim, self.maindim)	
=>
self.assertEqual(a1.maindim, self.maindim)
=> Final asserts changes

tables/tests/test_nestedtypes.py
this is mostly an FYI that you can clean up more python2 only code
Also there's a bug on line 666 (maybe that was a sign) where in the python2 branch you always set dflt='r' instead of dflt='%(default)s'
=> Fix bug in python2 version of test

.travis.yml
Add python 3.8 dev to travis
Cleanup .travis.yml: Use xenial for all builds
=> Travis CI: test against python 3.8-dev

appveyor.yml, requirements.txt
HDF5 1.10 is now in conda default
Drop HDF5 1.8
Drop mock depency
=> Clean up appveyor config

setup.py
Fixes #761 
In Python>=3.8 on Windows, CPython no longers searches for DLLs in
PATH. For `setup.py install` to work, we must force DLLs to be installed.
DLL are included as `data` only if found: Exit on error if DLL not found.
(It is not strictly necessary to force this on py < 3.8 on Windows, but easier to just force for all)
Wheel building (all OSes): Exit if a runtime is not found, to prevent
a wheel being build without the required runtime included.
=> Setup: force installation/inclusion of runtimes

setup.py, tables/__init__.py
Py3.8 no longer searches PATH for DLL loading. Do not try to
modify PATH on Windows+python>=3.8.
Change warning message on missing DLL to reflect new DLL resolution.
=> WIN: Py3.8 DLL resolution fix

tables/nodes/tests/test_filenode.py, tables/tests/common.py
On my Windows workstation, `import tables` takes 3.3 s, about 3 s of which are spent in `import pkg_resources`.
Importing `pkg_resources` is known to be excruciatingly slow. See https://github.com/pypa/setuptools/issues/510
This PR moves the import of pkg_resources to the single test function where pkg_resources is used.
=> Fix slow import of tables

RELEASE_NOTES.txt, setup.py
This way, the directories found by `pkg-config` have precedence over the other dirs. With Python3.9 on Debian, without this change the `setup.py` does not work.
=> Fix for Python3.9 on Debian

tables/idxutils.py
Using a light index with optlevel above 6 result in a float chunksize value, which gets pytables to crash soon after.
This fixes it.
=> Fix light index optlevel > 6 chunksize

tables/idxutils.py
When `expectedrows` is provided by the user as a float, a bunch of functions fall apart, esp functions like `create_index`.
When big number of expected rows, it is quite natural to write things like `1e9` and everything mostly works until playing with indexes.
One other option would be to fail early if expectedrows is provided as a float, or to cast it right away in the `__init__()` methods. Not sure what you guys prefer.
Error trace like the following are obtained when setting expectedrows to a float:
```
File "/usr/local/lib/python3.6/dist-packages/tables/table.py", line 3602, in create_index
tmp_dir, _blocksizes, _verbose)
File "/usr/local/lib/python3.6/dist-packages/tables/table.py", line 331, in _column__create_index
index.optimize(verbose=verbose)
File …
```
=> Fix computeblocksize computation to return an int (even with expectedrows a float)

tables/atom.py, tables/nodes/filenode.py, tables/tests/test_tables.py, tables/tests/test_tablesMD.py
Since `numpy=1.19` `array.tostring()` is deprecated and should be replaced with `array.tobytes()` ([numpy release note reference](https://numpy.org/devdocs/release/1.19.0-notes.html#numpy-ndarray-tostring-is-deprecated-in-favor-of-tobytes))
This PR changes all of them, it passes the small test suite. 
No bump of the minimal `numpy` version is needed, as `tobytes()` was implemented in `numpy>=1.9`, which is already the minimal requirement.
=> Solve numpy tostring DeprecationWarning

doc/source/conf.py, tables/atom.py, tables/attributeset.py, tables/hdf5extension.pyx, tables/nodes/tests/test_filenode.py, tables/tests/test_attributes.py, tables/tests/test_basics.py, tables/tests/test_vlarray.py, tables/utilsextension.pyx
On Python 2, `u"..."` string prefix is used to denote a unicode string where as on Python 3, all strings are unicode strings so the `u"..."` string prefix isnt needed. The changes were made by manually searching and replacing the occurances in the codebase.
=> Remove u string prefixes

tables/hdf5extension.pyx, tables/indexesextension.pyx, tables/tableextension.pyx, tables/utilsextension.pyx
`cython -3` complaining about not being able to cast double to int in these locations.
```
Error compiling Cython file:
------------------------------------------------------------
...
--
while lo < hi:
mid = (lo+hi)/2
^
------------------------------------------------------------
tables/utilsextension.pyx:253:17: Cannot assign type 'double' to 'int'
```
=> Use integer division

tables/hdf5extension.pxd, tables/hdf5extension.pyx, tables/indexesextension.pyx, tables/linkextension.pyx, tables/tableextension.pyx, tables/utilsextension.pxd, tables/utilsextension.pyx
Unify some cimports ("tables.<X>", "<X>", ".<X>") into ".<X>"
I tested this by running "pip install ." then "python3 -m tables.tests.test_all"
=> Make cimports explicitly relative

.github/workflows/ci.yml, README.rst, examples/multiprocess_access_queues.py, setup.py, tables/tests/test_attributes.py, tables/tests/test_basics.py
I assume the lowest supported Python version is 3.5.
Declare the support for 3.5–3.9 in PyPI classifiers, add badges to `README.rst` (the new classifiers will appear only after the next release) and fix the test for the lowest supported version in `setup.py`.
Add 3.5 to the GitHub CI as well.
Also remove some further pre-Python3.5 hacks from the code.
=> Declare support for Python 3.5–3.9 and remove older hacks

doc/scripts/filenode.py, doc/scripts/pickletrouble.py, doc/scripts/tutorial1.py, doc/source/FAQ.rst, doc/source/MIGRATING_TO_2.x.rst, doc/source/MIGRATING_TO_3.x.rst, doc/source/conf.py, doc/source/cookbook/hints_for_sql_users.rst, doc/source/cookbook/no_root_install.rst, doc/source/cookbook/py2exe_howto/pytables_test.py, doc/source/other_material.rst, doc/source/release-notes/RELEASE_NOTES_v0.8.rst, doc/source/release-notes/RELEASE_NOTES_v0.9.rst, doc/source/release-notes/RELEASE_NOTES_v1.0.rst, doc/source/release-notes/RELEASE_NOTES_v2.0.x.rst, doc/source/release-notes/RELEASE_NOTES_v2.1.x-pro.rst, doc/source/release-notes/RELEASE_NOTES_v2.1.x.rst, doc/source/release-notes/RELEASE_NOTES_v2.2.x-pro.rst, doc/source/release-notes/RELEASE_NOTES_v2.2.x.rst, doc/source/release-notes/RELEASE_NOTES_v2.4.x.rst, doc/source/release-notes/RELEASE_NOTES_v3.0.x.rst, doc/source/release-notes/RELEASE_NOTES_v3.2.x.rst, doc/source/release-notes/RELEASE_NOTES_v3.5.x.rst, doc/source/usersguide/index.rst, doc/source/usersguide/installation.rst, doc/source/usersguide/introduction.rst, doc/source/usersguide/libref/link_classes.rst, doc/source/usersguide/tutorials.rst, doc/source/usersguide/usersguide.rst
Fixed some typos in the doc. Modernized the example code snippets.
Then generated everything with `make html`, copied to the `pytables.github.com` repo, but the diff is much larger than expected due to some IE/class/… changes. The new version is also `3.6.2.dev0`, so probably we should run this update when the new release is ready.
=> Doc code and typos

tables/tableextension.pyx, tables/tests/test_indexes.py
The current test `test04_itersorted9` tested with `start=None, stop=None, step=-5`, so it did not always have to return the first row. Add a new `test04_itersorted10` test with `start=None, stop=None, step=-1` and fixed a line in `tableextensions.pyx` to include that last missing row.
Fixes #740
=> Add itersorted test for step=-1 and fix #740

setup.py
These are the first steps to #857:
1. fix two string typos and one `setup` parameter name `extras_require` that always raised an error until now
2. apply `black -l 79` to `setup.py`. No `isort` this time, because of the import problems of `Extension`. Will fix that later.
3. reformat strings and comments to fit into 79 chars
4. transform all strings to f-strings
5. use `pathlib.Path` to read/write project files. The `.glob` part for `inc_dirs` and `blosc_sources` comes later
=> First steps into modern `setup.py`

.github/workflows/ubuntu.yml
There was a failed run in #862:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/pillow/python3-pil_7.0.0-4ubuntu0.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
Fetched 9598 kB in 0s (33.5 MB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
The version on the server at that time was `http://security.ubuntu.com/ubuntu/pool/main/p/pillow/python3-pil_7.0.0-4ubuntu0.2_amd64.deb`
This will update the packages index before the installation.
=> Run `apt-get update` before installing ubuntu packages

bench/bsddb-table-bench.py, bench/postgres-search-bench.py, bench/pytables-search-bench.py, bench/recarray2-test.py, bench/shelve-bench.py, bench/sqlite-search-bench.py, doc/source/cookbook/custom_data_types.rst, doc/source/usersguide/tutorials.rst, examples/array4.py, examples/tutorial2.py, tables/atom.py, tables/hdf5extension.pyx, tables/tests/test_numpy.py, tables/tests/test_vlarray.py, tables/utilsextension.pyx
Float64 is gone with numpy 1.20, which causes doctests to fail
(https://bugzilla.redhat.com/show_bug.cgi?id=1914335).
>>> numpy.__version__
'1.19.4'
>>> [k for k in numpy.sctypeDict.keys() if str(k).lower().startswith('float')]
['float16', 'Float16', 'float32', 'Float32', 'float64', 'Float64', 'float128', 'Float128', 'float_', 'float']
>>> numpy.__version__
'1.20.0rc2'
>>> [k for k in numpy.sctypeDict.keys() if str(k).lower().startswith('float')]
['float16', 'float32', 'float64', 'float128', 'float_', 'float']
=> Use lowercase "float64" as numpy dtype

tables/atom.py, tables/filters.py
Python3.10 includes the class name in the TypeError string
for __init__(). This change allows the tests to pass in the new version,
but obviously breaks with older Pythons.
This patch is enough for the tests to pass in Fedora rawhide with the new python version, but obviously you need something that also works with python <= 3.9. So I'm opening this to get the discussion started ;)
=> doctest: adjust __init__ TypeError formatting

bench/evaluate.py, bench/expression.py, bench/open_close-bench.py, bench/postgres_backend.py, bench/sqlite-search-bench.py, bench/sqlite3-search-bench.py, doc/source/cookbook/custom_data_types.rst, tables/atom.py, tables/conditions.py, tables/description.py, tables/expression.py, tables/file.py, tables/group.py, tables/idxutils.py, tables/index.py, tables/leaf.py, tables/scripts/ptrepack.py, tables/table.py, tables/tests/common.py, tables/tests/test_all.py, tables/tests/test_array.py, tables/tests/test_attributes.py, tables/tests/test_enum.py, tables/tests/test_queries.py, tables/tests/test_tables.py
This is the follow-up of #864 consolidating all `import` statements across the repo.
First, all unused imports are deleted, then the Python2 `__future__` imports and then the rest to have the same names in the whole codebase.
When this is approved, I'd squash all commits within this PR to a single one.
There's one big chapter missing: `import tables as tb` (it's my proposal to use the `tb` alias). But that would be a bigger separate PR.
=> Consistent imports

tables/utilsextension.pyx
Tests in a downstream project started raising the following warning:
```
/home/sroet/miniconda3/envs/pyretis/lib/python3.9/site-packages/tables/__init__.py:24: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
from .utilsextension import (
```
This PR removes the alias
=> convert np.typeDict to np.sctypeDict

setup.py
I got an error, "AttributeError: module 'ctypes' has no attribute 'utils'", during installing in windows . The module ctypes.util is not imported by ctypes.
=> Add 'import ctypes.util'

.github/workflows/ci.yml, setup.py
Considering that python 3.10 is now released since quite some time, i think pytables should be running CI against this.
This seems to be possible without major issues - however it will ensure that compatibility with 3.10 is there (and remains there) by running the test-suite against python3.10 as well.
=> Run CI against python 3.10

.github/workflows/wheels.yml
Followup to #917, where i've forgotten to update this CI file to python 3.10 as well.
This will also close the following issues in my opinion (once released, obviously), (as i don't think they are about 3.6.1 specifically, but about the latest version of pytables): #911, #884
The output of the Ran pipeline will be as follows:
```
RELEASE_NOTES-3.6.2.dev0.txt
pytables-3.6.2.dev0.md5
pytablesmanual-3.6.2.dev0-html.tar.gz
pytablesmanual-3.6.2.dev0.pdf
tables-3.6.2.dev0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
tables-3.6.2.dev0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
tables-3.6.2.dev0-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
tables-3.6.2.dev0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl …
```
=> Build linux Wheels for 3.10

.github/workflows/ci.yml, appveyor.yml, setup.py
Enable CI on windows for python 3.9 and python 3.10.
Replaces #919 (i think this is the shortest/easiest way?) 
---
The offending line is `lib_dirs.append(Path(f'"{libdir}"'))` - which results in a quoted lib-dir 
This does not seem to cause issues up to python 3.8 - but results in LNK failures in 3.9 and up.
The line itself was added sometime in 2008 - but is no longer needed (and apparently, in new versions no longer supported).
The resulting linker command (`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:"C:\Miniconda37-x64\envs\build_env\Library\lib" [...]`) is wrongly/oddly quoted. 
Comparing outputs between this line for 3.9 and 3.8 shows that the quotes are set quite …
=> Enable CI on windows 3.9 and 3.10

README.rst
Readme should no longer show badge from travis, since travis is no longer used.
=> Readme should no longer show badge from travis

.github/workflows/wheels.yml
Add windows wheels and independent test to GHA
For the most part (especially the windows part), this is based on top of the great work from @amotl in #872.
Built wheels for ubuntu x64, windows (win32 and amd64) are tested in a second CI step.
This ensures that no hdf5 Build dependencies are installed, as these are fresh, new machines.
The build step also does not do the checkout step, so the original source is also not available (intentionally).
python for linux on x86 devices seems to be unavailable based on [this run](https://github.com/xmatthias/PyTables/runs/4526501674?check_suite_focus=true) - which shows that linux binaries are not available through the python setup action (i also don't think 32bit for linux is all too relevant).
**EDIT** You can find the last run which ran the …
=> Add windows wheels and independent test to GHA

.github/workflows/wheels.yml
Adding support for MacOS builds, for both x64 and arm64 builds.
Only the x64 are being tested - and I'd be grateful if someone can step up and try to install the arm64 binary on a M1 system.
A recent CI run for this can be found [here](https://github.com/xmatthias/PyTables/runs/4535307675?check_suite_focus=true).
This is based mostly on the great work from @amotl in #872
---
This is currently using the hdf5 (and blosc) library from brew (as well as some other libraries necessary for building).
While this might for sure be seen as controversial, i don't see this as worse than using libraries from conda (which pytables does and did for Windows CI already).
I'm also working on a "build hdf5 from source" PR - which will build hdf5 from source on linux/macos Systems - but the brew dependency …
=> Add CI wheel build for MacOS

.github/workflows/wheels.yml
Unfortunately, the wheels we're building for Macos Silicon (arm64 builds) are not working correctly.
As mentioned in #927, help will be needed to test the arm64 binary - which i've now gotten (but it went the wrong way).
I've had a friend with a mac M1 install the wheel from the latest master build, and unfortunately, the arm64 wheel has the error also highlighted in #887 - 
```
ImportError: dlopen(/opt/homebrew/lib/python3.8/site-packages/tables/utilsextension.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_H5E_CALLBACK_g'
```
I'm not sure we will be able to provide these wheels unless someone with an M1 (and some skills / patience) can help us get CI for this working (which may require additional changes to how the build process works - as i don't think this is a "ci …
=> Remove MacOS arm64 wheel 

.github/workflows/wheels.yml, ci/github/get_hdf5_if_needed.sh
This PR will add building hdf5 from source (therefore upgrading hdf5 to 1.12.1 - as requested in #912).
It'll also use the builtin blosc library for x86 wheels (this is optional and could be removed / reverted).
Wheels from my last run can be found [here](https://github.com/xmatthias/PyTables/actions/runs/1591055325) in the artifact download.
unfortunately, it does also include #929 - as i'm unable to build wheels from source on arm macos (and they didn't work anyway). 
I could make CI more complicated to keep this part separate, but i'm not sure that will make sense.
it'll also increase runtime for the wheel CI quite some - as the build on aarch64 happnes as cross-compile, which can only utilize one core. with 2.5 hours it's however still well within range of the 6h github action runtime …
=> Build hdf5 from source when building wheels

tables/utils.py
Hi there! I got burned trying to catch a `FileNotFoundError` in a script that loads some data (via deepdish, which uses tables internally)... and instead getting a nondescript `OSError`. I strongly feel that a more specific exception would make the checks done in `check_file_access()` much more useful.
I propose to substitute all uses of `OSError` with the [appropriate subclass exception](https://docs.python.org/3/library/exceptions.html#os-exceptions) for the particular case encountered. Note that, since all proposed substitutions are subclasses of `OSError`, existing exception handling mechanisms along the lines of `try: ... catch OSError: ...` will work just fine.
There doesn't seem to be a `NotARegularFileError`, sadly, but chances are that things that are `not path.isfile()` are …
=> Raise specific subclasses of OSError when checking file access

.github/workflows/wheels.yml
Bumps HDF5 version to 1.13.1.
1.13.0 introduced universal binaries for macos. I'm hoping if the upgrade works that we can also add universal wheel support.
=> Bump HDF5 version to 1.13.1.

ci/github/get_hdf5.sh
This bumps zlib the most recent release, that includes some security fixes.
The `export cc=$CC` change is needed to address https://github.com/madler/zlib/issues/615 until the next zlib is released.
Forgot that the branch needs to be named `ci/...` to build the wheels, so I created such a branch from this branch and you can see the wheels build here: https://github.com/matham/PyTables/actions/runs/2083777853.
=> Bump Mac wheel zlib version to latest release 1.2.12

.github/workflows/wheels.yml
Update CI to use 3.11 (non-dev).
This also requires packaging - which is listed in the pyproject.toml file - but not installed when testing the wheel installation.
Maybe for completeness - the CI run itself can be found [in my fork](https://github.com/xmatthias/PyTables/actions/runs/3350326122)
=> Use stable 3.11 for wheel testing

.github/workflows/ci.yml, .github/workflows/wheels.yml, ci/github/get_hdf5.sh, ci/osx_cross_configure.patch, ci/osx_cross_src_makefile.patch
- Bumps HDF5 to v1.12.2 and includes the required patch files in the repo instead of downloading it.
- It also removes some unneeded patches and env variables.
- Also spruced up the python versions used in the CI when testing or the baseline python.
=> Bump HDF5 to v1.12.2

tables/tests/common.py
PR for #940 as suggested here: https://github.com/PyTables/PyTables/issues/940#issuecomment-1062793552
Decided to use [packaging.version.parse()](https://packaging.pypa.io/en/stable/version.html#packaging.version.parse) since it does what was suggested in the comment.
I had the same exception seen in #940, and this change fixed it for me.
=> Fix for HDF5 version problems (Invalid version) (#940)

tables/parameters.py
With mkl installed, setting this environment variable will trigger a "TypeError: an integer is required (got type str)" from numexpr's `set_vml_num_threads` call that comes from the last line of `File.__init__,` since environment variables are strings. 
Here's the code relevant code flow without this patch supposing I set `NUMEXPR_MAX_THREADS=8` before running python:
On import of parameters module, the variable gets set to a string.
https://github.com/PyTables/PyTables/blob/b9c9ac1a06341e0e80753b2ac72d50fd3d38da88/tables/parameters.py#L208
So `parameters.MAX_NUMEXPR_THREADS = '8'` and then in File's `__init__` it gets copied over
https://github.com/PyTables/PyTables/blob/b9c9ac1a06341e0e80753b2ac72d50fd3d38da88/tables/file.py#L727-L729
before finally being passed along to numexpr (which …
=> support NUMEXPR_MAX_THREADS environment variable

.github/workflows/wheels.yml
See https://github.com/PyTables/PyTables/pull/979.
=> Run osx arm64 and x86 builds in different containers to prevent binary clash

.github/workflows/ci.yml, setup.py
=> Allow to use of system blosc2 to build pytables

src/utils.c
Small cleanup as these haven't been used since [5a3f8367c0acf20c27fc2779d8abb8d71f6062c2](https://github.com/PyTables/PyTables/commit/5a3f8367c0acf20c27fc2779d8abb8d71f6062c2#diff-3e04e056edbdc0f772b0ffd1c93cef1187209f37276d40d2a281d9b989398a73)
=> Remove unused imports

tables/linkextension.pyx, tables/tests/test_links.py
Hi,
this PR fixes the mentioned issue. ptrepack copies nodes recursively with the `use_hardlink` flag activated. This flag calls the _get_obj_info() method to check the address and reference count (rc). As ExternalLinks do no get an objectid assigned by HDF5, this call fails. 
my fix overwrites the _get_obj_info() method for ExternalLinks and returns a fix tuple (0, 1).
Note that for SoftLinks this fix is not needed as the _get_obj_info() method gets evaluated on the target node as the __getattribute__ method dereferences all method calls.
=> fixes #938 (ptrepack fails with ExternalLinks)

src/H5TB-opt.c, tables/tableextension.pyx, tables/tests/test_large_tables.py, tables/tests/test_suite.py
This PR fixes #995.  Now the optimized path for blosc2 can properly create tables with more than 2**31 rows.
=> Use hsize_t for offsets (fixes #995)

.github/workflows/wheels.yml, hdf5-blosc2/src/blosc2_filter.c, src/H5TB-opt.c, src/H5TB-opt.h, tables/definitions.pxd, tables/table.py, tables/tableextension.pyx
Here there is an optimization for using `H5Dchunk_iter`.  This was originally suggested in https://github.com/PyTables/PyTables/issues/991 by @mkitti.
This should be only useful when there is a large number of chunks on a dataset, and one wants to walk all or a large part of it.  Preliminary benchmarks are suggesting that we can get up to 10% of speedup for datasets of 270 GB (7731 chunks when they are 36 MB in size), when using the optimized path for Blosc2.  Probably we can get more speedup for larger datasets (to be tested).
=> Optimization for iter chunk

bench/read-table.py, src/H5TB-opt.c, tables/table.py, tables/tableextension.pyx
Here it is yet another optimization for doing random reads in combination with the new `H5Dchunk_iter` introduced in HDF5 1.14 series.
The new `bench/read-table.py` script generates a table with 20 *billions* of rows, accounting for more than 2 million of chunks on my machine (as the chunk size is determined automatically based on the L3 size, this figure is machine dependent).  With that, here it is the new random speed when using HDF5 1.14.0:
```
Reading 100.0 Krows...
Time to read: 1.459s
```
which makes for 15 us per read; pretty good.
Using a build with HDF5 1.12.2 (i.e. not having the `H5Dchunk_iter` machinery), I'm getting:
```
Reading 100.0 Krows...
Time to read: 7.302s
```
so, 5x times slower.
As this depends on the square of the number of chunks, the improvement can be larger …
=> Optimize for H5Dchunk_iter for random reads

.github/workflows/ci.yml, .github/workflows/ubuntu.yml, doc/source/usersguide/installation.rst, pyproject.toml, requirements.txt, setup.py, tables/__init__.py, tables/req_versions.py
This is a bit different than #983, but works for my packaging efforts on openSUSE. I thought I should share. Feel free to use it in #983 or modify.
=> Search for libblosc2 with pkg-config if not in the python blosc2 installation

.github/workflows/ci.yml, .github/workflows/ubuntu.yml, .github/workflows/wheels.yml
Closes #1006 
- ubuntu.yml - success run https://github.com/joycebrum/PyTables/actions/runs/4418480233
- ci.yml - success run https://github.com/joycebrum/PyTables/actions/runs/4418480235
- wheels.yml - it is with the same errors https://github.com/joycebrum/PyTables/actions/runs/4418480249. I believe the permissions granted (`contents: read`) will be enough to this workflow, looking at the jobs.
If you have any problem with wheels.yml permission after fixing it feel free to ping me and I'll be happy to help. I also tried to figure out why it is not working but also not sure about it 😥 .
=> Set github workflow permissions to least privileges

tables/leaf.py
Fallback gracefully if py-cpuinfo isn't installed. We already handle this in setup.py but we need to avoid calling it in leaf.py too.
=> Handle py-cpuinfo not being installed

doc/source/usersguide/installation.rst, setup.py
=> Improve blosc2 detection

tables/file.py
Currently the documentation of [`get_node`](https://www.pytables.org/usersguide/libref/file_class.html#tables.File.get_node) is a bit garbled as Sphinx tries to format the last paragraph as parameters:
Fixed by formatting this paragraph as a note.
=> DOC: fix get_node docstring formatting

bench/optimal-chunksize.py
In file: optimal-chunksize.py, there is a method  that creates a temporary file using an unsafe API mktemp. The use of this method is discouraged in the Python_documentation. iCR suggested that a temporary file should be created using NamedTemporaryFile which is a_safe_API. iCR replaced the usage of mktemp with NamedTemporaryFile.
It is important to note that this method is considered insecure which is also mentioned in the original documentation of tempfile package. This insecurity stems from the fact that the process of creating a file using the mktemp() function occurs in two distinct steps. Initially, a filename is generated, and subsequently, a file is created using that particular name. This process becomes insecure due to the possibility that a separate process might generate a …
=> Replace unsafe mktemp function in code

doc/source/release_notes.rst
The latest releases where missing; added them with the dates when their respective Git tags where created.
Also fix a typo in the PyTables 0.9 line.
=> Fix and update release timeline in release notes

ANNOUNCE.txt.in, RELEASE_NOTES.rst, doc/source/usersguide/installation.rst, pyproject.toml, tables/_version.py
This is a proposal for a hot release for deprecating the support of Python 3.8.  For details, see: https://github.com/PyTables/PyTables/issues/1062 and https://github.com/PyTables/PyTables/issues/1061.  The hot release will be just a new set of wheels and sources, without regenerating docs or anything else.  The idea is that people get a quick error when they try to use PyTables 3.9.1 when using Python 3.8
=> Preliminaries for 3.9.1 release

bench/bench-pytables-ranges.sh, bench/bench-pytables.sh, doc/source/cookbook/inmemory_hdf5_files.rst, doc/source/usersguide/installation.rst, setup.py, src/utils.c, src/utils.h, tables/__init__.py, tables/definitions.pxd, tables/hdf5extension.pyx, tables/indexesextension.pyx, tables/parameters.py, tables/tableextension.pyx, tables/tests/test_create.py, tables/tests/test_types.py, tables/utilsextension.pyx
Compatibility with HDF5 1.8.x is no longer needed, so we can switch to the newer API
=> Switch to H5_USE_110_API

tables/leaf.py
get_cpu_info takes a relative long time (> 1s on my machine), resulting in very long import times for tables.
Fixed by only getting it when needed and caching the result.
=> Reduce import time of tables.leaf.

hdf5-blosc2/src/blosc2_filter.c
Fixes https://github.com/PyTables/PyTables/issues/1109
=> Set schunk when decompressing

tables/leaf.py
This is yet another fix related to the discussion in issue #1081 
Benefit of this approach:
- the file cache will be available for different processes
- the cpuinfo needs to be processed only once per machine/user
Json format was the first that came to my mind. It could be changed to something else.
=> Store cpuinfo in a cache file for performance

tables/node.py
Hello,
I added type hints to `tables/node.py`.
Note: at the beginning I used 
~~~
if TYPE_CHECKING:
from .group import Group
from .link import SoftLink
~~~
This is to prevent circular imports as the `tables/group.py` already imports the `tables/node.py`. 
By putting the needed imports behind a [typing.TYPE_CHECKING](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING) flag (which always evaluates to `False`), we can use the full type hint support without any need for refactoring.
Best regards
Ko
=> Add type hints to node.py

tables/leaf.py
Hello,
I fixed the `Leaf.copy` method by providing `createparents` as a keyword argument as mentioned in #1125 
Best regards,
Ko
=> Fix Leaf.copy by providing the correct value to createparents parameter

tables/carray.py, tables/earray.py, tables/vlarray.py
Hello,
I added annotations to `tables/carray.py`, `tables/earray.py`and `tables/vlarray.py`.
As they are pretty similar, I combined them into a single pull request.
Best regards
Ko
=> Add type hints to CArray, EArray and VLArray

tables/__init__.py
Hello,
I added annotations to `tables/__init__.py`.
With that, all the functions and methods in `tables` should have annotations now.
Kind regards
Ko
=> Add type hints to __init__.py

.github/workflows/wheels.yml
This is a fairly trivial PR to make it so the wheel build runs on PRs. I think it was meant to before as well but the `pull_request:` block was indented too far.
Assuming this is okay, please merge (whatever the CI status is) and then I'll work on actually fixing the broken wheel build. (If I try to fix it in this PR, it will probably require maintainer approval with every commit which won't work well. Once this is merged GitHub will trust me enough in the next PR that I can push commits and CIs will run.)
=> BUG: Fix bug with pull_request level

.github/workflows/wheels.yml, pyproject.toml, setup.py, tables/__init__.py
Poking around I noticed `master` is failing due to a `delvewheel` problem where it can't find `libblosc2`. I think installing it from conda might be enough to fix it, but we'll see :crossed_fingers:
=> MAINT: Fix delvewheel Windows error

doc/source/usersguide/optimization.rst, hdf5-blosc/src/example.c, hdf5-blosc2/src/blosc2_filter.c, src/H5ARRAY-opt.c, src/H5ARRAY.c, src/H5TB-opt.c, src/H5VLARRAY.c, tables/hdf5extension.pyx, tables/tableextension.pyx, tables/tests/test_carray.py, tables/tests/test_earray.py
This changes the default filter order to put the Fletcher32 filter at the end of the pipeline, after compression filters. This doesn't make much difference for byte-oriented compressors, but it does for B2ND compression since it understands the structure of data in the chunk. If the Fletcher32 checksum was added before compression to the end of the buffer passed to the Blosc2 filter, it just ignored that data, which caused checksum verification issues on decompression.
By performing and adding the checksum after compression, the compressor doesn't need to worry about the checksum being there (nor does decompression). Of course, this means that enabling Fletcher32 adds 4 bytes to each chunk, but compressing them as part of the data didn't make much sense either.
Some checks have been added …
=> Fix B2ND compression with  Fletcher32

pyproject.toml, tables/tests/test_all.py
I noticed that the scheduled `nightly` wheel build didn't finish:
https://github.com/PyTables/PyTables/actions/runs/10340087060/job/28620253697
But it's very difficult to parse the log because of the *very* long `pip` output. I want to reduce that and fix the build if necessary.
=> MAINT: Lower verbosity in wheel build

tables/tests/test_direct_chunk.py
Pass `refcheck=False` when resizing an `np.ndarray` in place, in order to fix a test failure on PyPy3:
```pytb
Traceback (most recent call last):
File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 266, in test_write_chunk_missing1
return self._test_write_chunk_missing(shrink_after=False)
File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 255, in _test_write_chunk_missing
new_obj.resize(self.array.shape)
ValueError: cannot resize an array with refcheck=True on PyPy.
Use the np.resize function or refcheck=False
```
Since the object is created immediately above the `.resize()` call, adding `refcheck=False` should be entirely safe.  Furthermore, unlike `np.resize()` this preserves the current behavior when new shape is larger than the original.
Fixes #1202
=> FIX: Pass `refcheck=False` to `np.ndarray.resize()` for PyPy compat

tables/description.py, tables/file.py, tables/table.py
Updates the type hints on `File.create_table`'s `description` argument to allow `dict`, `numpy.dtype`, and `Type[IsDescription]` in addition to `Description`. This matches both the actual functionality, and the type hints of `Table.__init__`.
=> Type hints: Accept IsDescription, dict, numpy.dtype as table descriptions

tables/leaf.py
fixes issue #1221. 
If ~/.pytables-cpuinfo.json cannot be written (e.g. readonly), the cpu info will now simply 
be cached during the process lifespan (lru-cache) and will need to be recomputed in the next
process.
=> fixes error writing cpu info to cache file

setup.py
This fixes failures  of ctypes.CDLL() to find locate dylibs on macOS, per #1219.
=> Patch to find runtime dir on macOS

.github/workflows/wheels.yml, ci/github/get_hdf5.sh
1. Fix broken URL and associated dir structure
2. Change from emulation to native building using new publicly available Ubuntu arm64 runner
3. Update to latest HDF5 release
4. Add `workflow_dispatch` trigger
Takes care of https://github.com/PyTables/PyTables/issues/1115#issuecomment-2678888676
=> MAINT: Fix wheel build and use native aarch64 runner
