PyTables/PyTables

- setup.py
Correctly bootstrapping numpy in setup.py is practically impossible but I am trying to follow what is done in pandas. Their approach is mostly based on http://stackoverflow.com/a/21621689/104099.
> Correctly bootstrap numpy in setup.py

- tables/attributeset.py
- tables/path.py
- tables/tests/test_attributes.py
> Allow slashes in attribute names

- RELEASE_NOTES.txt
- tables/table.py
- tables/tests/test_tables.py
Removed the condition blocking the removal of all rows from a table. The new test passed.
> remove_rows can remove all rows

- RELEASE_NOTES.txt
- c-blosc/hdf5/blosc_filter.c
- c-blosc/hdf5/blosc_filter.h
- setup.py
- tables/__init__.py
I'm updating it to work with the CMake built HDF5 1.8.16 in Windows.
I've also picked a commit from c-blosc that fixes it for HDF5 1.8.16.
> Update to use HDF5 1.8.16 (naming and minor API changes)

- README.rst
- RELEASE_NOTES.txt
- doc/source/usersguide/installation.rst
- doc/source/usersguide/libref/helper_classes.rst
- doc/source/usersguide/optimization.rst
- doc/source/usersguide/tutorials.rst
- doc/source/usersguide/utilities.rst
- hdf5-blosc/src/blosc_filter.c
- requirements.txt
- setup.py
- src/H5ARRAY.c
- src/H5TB-opt.c
- src/H5VLARRAY.c
- tables/filters.py
- tables/hdf5extension.pyx
- tables/index.py
- tables/leaf.py
- tables/parameters.py
- tables/req_versions.py
- tables/scripts/ptrepack.py
- tables/tableextension.pyx
- tables/tests/common.py
- tables/tests/test_all.py
- tables/tests/test_carray.py
- tables/tests/test_create.py
- tables/tests/test_hdf5compat.py
- tables/tests/test_tables.py
- tables/tests/test_vlarray.py
After Blosc 1.8.1 integration, I decided to implement full support for the bitshuffle filter.  It would be nice if someone can provide a review.
> Bitshuffle support

- tables/scripts/ptrepack.py
Every time I use pytables (manipulating HDF5 files from pandas) I have to manually change these 2 lines. May be they could be added to the 'master' branch.
What do you think ?
> accept windows drive letter in path

- RELEASE_NOTES.txt
- tables/atom.py
long -> six.integer_types
Fixes gh-598
Maybe need to add regression test...
> Fix 2to3 conversion of long

- cpuinfo.py
That old cpuinfo.py script didn't detect ppc64 properly:
$ pip install tables
Collecting tables
Downloading tables-3.3.0.tar.gz (7.0MB)
100% |████████████████████████████████| 7.0MB 179kB/s
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-v71heqso/tables/setup.py", line 35, in <module>
import cpuinfo
File "/tmp/pip-build-v71heqso/tables/cpuinfo.py", line 1565, in <module>
_check_arch()
File "/tmp/pip-build-v71heqso/tables/cpuinfo.py", line 1522, in _check_arch
raise Exception("py-cpuinfo currently only works on X86 and some ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some ARM CPUs.
----------------------------------------
Command "python setup.py egg_info" failed with …
> Update cpuinfo.py in order to work on ppc64

- doc/source/cookbook/custom_data_types.rst
> Docs: cookbook: update inherit from Table

- doc/source/cookbook/inmemory_hdf5_files.rst
> * doc/source/cookbook/inmemory_hdf5_files.rst: Grammar fix.

- CITATION.bib
- doc/source/FAQ.rst
@FrancescAlted thinks that is time to go ahead and give to the team the merit they deserve.
> Changes author to PyTables Developers Team

- tables/tests/test_attributes.py
Sorry about the spam, I mistakenly lower cased the i in Instance in #748 was wasn't able to reopen, fixed now.
> Use assertIsInstance in tests

- tables/tests/test_attributes.py
- tables/tests/test_basics.py
- tables/tests/test_create.py
- tables/tests/test_expression.py
- tables/tests/test_hdf5compat.py
- tables/tests/test_indexes.py
- tables/tests/test_numpy.py
- tables/tests/test_queries.py
- tables/tests/test_tables.py
- tables/tests/test_tree.py
- tables/tests/test_types.py
Replace all assertTrue(isinstance(...)) with assertIsInstance(...)
and also some assertFalse with assertNotIsIntance
> Use assertIsInstance in more tests

- tables/tests/test_array.py
- tables/tests/test_attributes.py
- tables/tests/test_basics.py
- tables/tests/test_carray.py
- tables/tests/test_create.py
- tables/tests/test_do_undo.py
- tables/tests/test_enum.py
- tables/tests/test_expression.py
- tables/tests/test_hdf5compat.py
- tables/tests/test_index_backcompat.py
- tables/tests/test_indexes.py
- tables/tests/test_indexvalues.py
- tables/tests/test_links.py
- tables/tests/test_nestedtypes.py
- tables/tests/test_queries.py
- tables/tests/test_tables.py
- tables/tests/test_timetype.py
- tables/tests/test_tree.py
- tables/tests/test_types.py
Thanks for pulling these changes, they are not the most glamorous but make debugging tests much easier
> Cleanup more asserts

- doc/source/usersguide/tutorials.rst
Hello,
The first part of the tutorial is excellent. I fixed some sporadic typos and language issues here and there. The latter part of the document could use more work. I did my best to rephrase, where necessary. Some paragraphs were rewritten completely. While I believe it is an improvement, I would advise the following chapters to be rewritten:
- Enums
- Enum columns
- Enumerated arrays
- Undo & Redo
- Nested columns
- Nested tables
Improvements in this pull request could be used as a starting point.
Thank you,
dearkarm
> Various updates & fixes to tutorials.rst

- tables/attributeset.py
I don't know if this is the right approach to solving #811, but it makes the files readable at least!
> Ignore failed parsing of FILTERS attribute, fixes #811

- .github/workflows/ci.yml
Convert the Test CI from Travis to GitHub Actions.
> Add GitHub Actions for Tests

- README.rst
> Add github actions badge to README.rst

- examples/array4.py
> Fix example array4

- setup.py
This is a follow-up of #858 with most `os.path` and `glob` calls replaced by `pathlib.Path`, except for `hdrdir` and `libdir` manipulation that has to be investigated separately because it can optionally hold a boolean variable.
Since there are no tests, it has to be reviewed manually. `python setup.py sdist` runs through though.
> Use pathlib to glob files in setup.py

- hdf5-blosc/src/blosc_filter.c
- setup.py
- src/idx-opt.c
- src/idx-opt.h
- src/typeconv.h
- src/utils.c
- src/utils.h
- tables/hdf5extension.pyx
- tables/indexesextension.pyx
- tables/lrucacheextension.pyx
- tables/tableextension.pyx
- tables/utilsextension.pyx
The tests pass, but I didn't do any benchmarking...
> Remove calls to numpy deprecated APIs

- .github/workflows/wheels.yml
Added linux aarch64 wheel support.
Related to #891. @avalentino Could you please review this PR.
> Add linux aarch64 wheel support

- .github/workflows/wheels.yml
- setup.cfg
- setup.py
New wheels are available at: https://github.com/avalentino/PyTables/actions/runs/1659070310
> Remove duplicate DLLs in windows wheels (Closes: #932)

- tables/attributeset.py
- tables/exceptions.py
- tables/file.py
> Use python warnings instead of messages to sys.stderr, fixes #992

- .github/workflows/wheels.yml
- doc/source/usersguide/installation.rst
- pyproject.toml
- requirements.txt
Results of the workflows/wheels.yml can be checked at https://github.com/avalentino/PyTables/actions
> Fix wheels workflow

- .github/workflows/wheels.yml
- RELEASE_NOTES.rst
- ci/github/get_hdf5.sh
> Update external libraries

- tables/__init__.py
> Improve checks for blosc2 availability

- RELEASE_NOTES.rst
- tables/tests/test_queries.py
> Fix compatibility with numexpr v2.8.5

- RELEASE_NOTES.rst
- ci/github/get_hdf5.sh
https://github.com/PyTables/PyTables/issues/1075
> Use threadsafe hdf5 for python wheel

- tables/misc/enum.py
Hello,
I added annotations to the `tables/enum.py` code.
Kind regards
Ko
> Add type hints to enum.py

- tables/file.py
Hello,
I added annotations to `tables/file.py`.
Best regards
Ko
> Add type hints to file.py

- tables/atom.py
- tables/file.py
- tables/index.py
Hello,
some docstrings were missing descriptions for some parameters. I filled them in.
Kind regards
Ko
> Update missing parameter descriptions in docstrings

- tables/array.py
Hello,
I added annotations to `table/array.py`.
Kind regards
Ko
> Add type hints to array.py

- tables/filters.py
Hello,
I added annotations to `tables/filters.py`.
Best regards
Ko
> Add type hints to filters.py

- tables/flavor.py
Hello,
I added annotations to `tables/flavor.py`.
Best regards
Ko
> Add type hints to flavor.py

- tables/idxutils.py
Hello,
I added annotations to `tables/idxutils.py`.
Best regards
Ko
> Add type hints to idxutils.py

- tables/indexes.py
Hello,
I added annotations to `tables/indexes.py`.
Best regards
Ko
> Add type hints to indexes.py

- tables/index.py
- tables/indexes.py
Hello,
I added annotations to `tables/index.py`.
Further, there is small annotation fix in `tables/indexes.py`.
Best regards
Ko
> Add type hints to index.py

- tables/undoredo.py
Hello,
I added annotations to `tables/undoredo.py`.
Kind regards
Ko
> Add type hints to undoredo.py

- tables/unimplemented.py
Hello,
I added annotations to `tables/unimplemented.py`.
Kind regards
Ko
> Add type hints to unimplemented.py

- tables/attributeset.py
Hello,
I added annotations to `tables/attributeset.py`.
Kind regards
Ko
> Add type hints to attributeset.py

- tables/link.py
Hello,
I added annotations to `tables/link.py`.
Best regards
Ko
> Add type hints to link.py

- tables/description.py
Hello,
I added annotations to `tables/description.py`.
The annotations were a bit tricky sometimes since we handling with class objects instead of instances of classes here.
For this, the `typing.Type` hint was used. See also
- https://docs.python.org/3.9/library/typing.html#typing.Type
Best regards
Ko
> Add type hints to description.py

- tables/group.py
Hello,
I added annotations to `tables/group.py`.
Best regards
Ko
> Add type hints to group.py

- tables/registry.py
Hello,
I added annotations to `tables/registry.py`.
Best regards
Ko
> Add type hints to registry.py

- tables/utils.py
Hello,
I added annotations to `tables/utils.py`.
Best regards
Ko
> Add type hints to utils.py

- tables/conditions.py
Hello,
I added annotations to `tables/conditions.py`.
This was a pretty tough one, so I am a bit unsure myself if everything is correct.
Best regards
Ko
> Add type hints to conditions.py

- tables/expression.py
Hello,
I added annotations to `tables/expression.py`.
This was another tough one.
Best regards
Ko
> Add type hints to expression.py

- tables/array.py
* Add redirect to https://github.com/PyTables/PyTables/issues/1149
> Points users to help for dealing with duplicate indices

- tables/tests/common.py
- tables/tests/test_queries.py
...as test_queries.py uses it.
> Make tables.tests.common.make_suite() accept the prefix argument
